### PR TITLE
Adicionado environment

### PR DESCRIPTION
**Pull request by dennysfredericci**
Adicionado plugin do environment

### CODE REVIEW

**Comment by garcia-jj** [comment]
I can't accept this pull request because:
- why you change the scm entry in poom.xml?
- don't change files identation
- to maintain compatibility with hibernate3 plugin, we need to use hibernate.cfg.xml (not .properties)

Thank you

**Comment by dennysfredericci** [comment]
Hi Garcia!

Q: why you change the scm entry in poom.xml?
A: Sorry about that, i changed to use with my maven repository,  i can fix it

Q: don't change files identation
A: I use a default eclipse configuration and CTRL + SHIFT + F to formatting my code, is a wrong way?

Q: o maintain compatibility with hibernate3 plugin, we need to use hibernate.cfg.xml (not .properties)
Do you need compatibility with hibernate3 plugin ? Why? If i need hibernate 3 just use hibernate 3 plugin or not?

Thanks!  ;)

**Comment by garcia-jj** [comment]
> Do you need compatibility with hibernate3 plugin ? Why? If i need hibernate 3 just use hibernate 3 plugin or not?

Hibernate 3 plugin uses hibernate.cfg.xml. Users that want to migrate to this plugin want to do this without change from xml to properties. So this plugin needs to use xml too.

**Comment by garcia-jj** [comment]
Please, take a look here: https://github.com/garcia-jj/vraptor-plugin-hibernate4/tree/environment

In this branch there are a untested version with environment.

**Comment by garcia-jj** [comment]
Merged, thank you.

**Pull request closed without merging**
